In [6]:
import nltk

In [7]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/angelgabrieltovargarcia/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [8]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize 
from nltk.tokenize import RegexpTokenizer
import numpy as np    
from numpy import dot
from numpy.linalg import norm

In [9]:
stopwords.fileids()

['arabic',
 'azerbaijani',
 'danish',
 'dutch',
 'english',
 'finnish',
 'french',
 'german',
 'greek',
 'hungarian',
 'indonesian',
 'italian',
 'kazakh',
 'nepali',
 'norwegian',
 'portuguese',
 'romanian',
 'russian',
 'slovene',
 'spanish',
 'swedish',
 'tajik',
 'turkish']

In [10]:
set(stopwords.words('spanish'))

{'a',
 'al',
 'algo',
 'algunas',
 'algunos',
 'ante',
 'antes',
 'como',
 'con',
 'contra',
 'cual',
 'cuando',
 'de',
 'del',
 'desde',
 'donde',
 'durante',
 'e',
 'el',
 'ella',
 'ellas',
 'ellos',
 'en',
 'entre',
 'era',
 'erais',
 'eran',
 'eras',
 'eres',
 'es',
 'esa',
 'esas',
 'ese',
 'eso',
 'esos',
 'esta',
 'estaba',
 'estabais',
 'estaban',
 'estabas',
 'estad',
 'estada',
 'estadas',
 'estado',
 'estados',
 'estamos',
 'estando',
 'estar',
 'estaremos',
 'estará',
 'estarán',
 'estarás',
 'estaré',
 'estaréis',
 'estaría',
 'estaríais',
 'estaríamos',
 'estarían',
 'estarías',
 'estas',
 'este',
 'estemos',
 'esto',
 'estos',
 'estoy',
 'estuve',
 'estuviera',
 'estuvierais',
 'estuvieran',
 'estuvieras',
 'estuvieron',
 'estuviese',
 'estuvieseis',
 'estuviesen',
 'estuvieses',
 'estuvimos',
 'estuviste',
 'estuvisteis',
 'estuviéramos',
 'estuviésemos',
 'estuvo',
 'está',
 'estábamos',
 'estáis',
 'están',
 'estás',
 'esté',
 'estéis',
 'estén',
 'estés',
 'fue',
 'f

In [11]:
tokenizer = RegexpTokenizer(r'\w+')

In [12]:
#Experimiento Tweet 1
texto_01 = "Si Bimbo pretende seguir oponiéndose al Etiquetado Claro, una medida que puede salvar y mejorar la vida de miles de niños frente a la obesidad y la diabetes, quizá deberíamos plantearnos sacarlos de nuestra cotidianidad."

In [13]:
print(texto_01)

Si Bimbo pretende seguir oponiéndose al Etiquetado Claro, una medida que puede salvar y mejorar la vida de miles de niños frente a la obesidad y la diabetes, quizá deberíamos plantearnos sacarlos de nuestra cotidianidad.


In [14]:
texto_02 = "No hay constancia de que poner ese etiquetado salve miles de vidas. Si no disminuyó el consumo de comida chatarra el IEPS que metieron precisamente como fin de inhibir el consumo, o las imágenes gráficas en las cajetillas, difícilmente un etiquetado hará la diferencia"

texto_03 = "Pregunta sería. ¿Por que insisten en invitar a Ijustine a los eventos de Samsung si TODOS sabemos que es una Apple fan boy? En serio se ve muy falsa fingiendo interés."

texto_04 = "para celebrar San Valentin les voy a contar la historia de cuando tuve un novio húngaro y un día sin querer, en una reunión familiar, casi mato a su abuelita con Tajín... AGÁRRENSE"

texto_05 = "Y pregunto porque se estuvieron llenando el hocico sus fans de que iba a sacar su propia línea de maquillaje y no sé qué más mierdas."

In [15]:
print(texto_02,texto_03, texto_04, texto_05)

No hay constancia de que poner ese etiquetado salve miles de vidas. Si no disminuyó el consumo de comida chatarra el IEPS que metieron precisamente como fin de inhibir el consumo, o las imágenes gráficas en las cajetillas, difícilmente un etiquetado hará la diferencia Pregunta sería. ¿Por que insisten en invitar a Ijustine a los eventos de Samsung si TODOS sabemos que es una Apple fan boy? En serio se ve muy falsa fingiendo interés. para celebrar San Valentin les voy a contar la historia de cuando tuve un novio húngaro y un día sin querer, en una reunión familiar, casi mato a su abuelita con Tajín... AGÁRRENSE Y pregunto porque se estuvieron llenando el hocico sus fans de que iba a sacar su propia línea de maquillaje y no sé qué más mierdas.


In [16]:
#Tokenizar
#Se utiliza la funcion para quitar los signos de puntuacion.
#texto numero 01
texto_01_token = tokenizer.tokenize(texto_01.lower())

In [17]:
print(texto_01_token)

['si', 'bimbo', 'pretende', 'seguir', 'oponie', 'ndose', 'al', 'etiquetado', 'claro', 'una', 'medida', 'que', 'puede', 'salvar', 'y', 'mejorar', 'la', 'vida', 'de', 'miles', 'de', 'nin', 'os', 'frente', 'a', 'la', 'obesidad', 'y', 'la', 'diabetes', 'quiza', 'deberi', 'amos', 'plantearnos', 'sacarlos', 'de', 'nuestra', 'cotidianidad']


In [18]:
texto_01_token_wout_stopwords = []
print(texto_01_token_wout_stopwords)

[]


In [19]:
for word in texto_01_token:
    if word not in stopwords.words('spanish'): texto_01_token_wout_stopwords.append(word)

print(texto_01_token_wout_stopwords)

['si', 'bimbo', 'pretende', 'seguir', 'oponie', 'ndose', 'etiquetado', 'claro', 'medida', 'puede', 'salvar', 'mejorar', 'vida', 'miles', 'nin', 'frente', 'obesidad', 'diabetes', 'quiza', 'deberi', 'amos', 'plantearnos', 'sacarlos', 'cotidianidad']


In [20]:
#Texto numero 02
texto_02_token = tokenizer.tokenize(texto_02.lower())

texto_02_token_wout_stopwords = []

for word in texto_02_token:
    if word not in stopwords.words('spanish'): texto_02_token_wout_stopwords.append(word)
        
print(texto_02_token_wout_stopwords)

['constancia', 'poner', 'etiquetado', 'salve', 'miles', 'vidas', 'si', 'disminuyo', 'consumo', 'comida', 'chatarra', 'ieps', 'metieron', 'precisamente', 'fin', 'inhibir', 'consumo', 'ima', 'genes', 'gra', 'ficas', 'cajetillas', 'difi', 'cilmente', 'etiquetado', 'hara', 'diferencia']


In [21]:
#Texto numero 03
texto_03_token = tokenizer.tokenize(texto_03.lower())

texto_03_token_wout_stopwords = []

for word in texto_03_token:
    if word not in stopwords.words('spanish'): texto_03_token_wout_stopwords.append(word)

print(texto_03_token_wout_stopwords)

['pregunta', 'seri', 'insisten', 'invitar', 'ijustine', 'eventos', 'samsung', 'si', 'sabemos', 'apple', 'fan', 'boy', 'serio', 've', 'falsa', 'fingiendo', 'intere', 's']


In [22]:
#Texto numero 04
texto_04_token = tokenizer.tokenize(texto_04.lower())

texto_04_token_wout_stopwords = []

for  word in texto_04_token:
    if word not in stopwords.words('spanish'): texto_04_token_wout_stopwords.append(word)
        
print(texto_04_token_wout_stopwords)

['celebrar', 'san', 'valentin', 'voy', 'contar', 'historia', 'novio', 'hu', 'ngaro', 'di', 'querer', 'reunio', 'n', 'familiar', 'casi', 'mato', 'abuelita', 'taji', 'n', 'aga', 'rrense']


In [23]:
#Texto numero 05
texto_05_token = tokenizer.tokenize(texto_04.lower())

texto_05_token_wout_stopwords = []

for word in texto_05_token:
    if word not in stopwords.words('spanish'): texto_05_token_wout_stopwords.append(word)
        
print(texto_05_token_wout_stopwords)

['celebrar', 'san', 'valentin', 'voy', 'contar', 'historia', 'novio', 'hu', 'ngaro', 'di', 'querer', 'reunio', 'n', 'familiar', 'casi', 'mato', 'abuelita', 'taji', 'n', 'aga', 'rrense']


In [24]:
print(len(texto_01_token_wout_stopwords))
print(len(texto_02_token_wout_stopwords))
print(len(texto_03_token_wout_stopwords))
print(len(texto_04_token_wout_stopwords))
print(len(texto_05_token_wout_stopwords))
print(len(texto_01_token_wout_stopwords)+len(texto_02_token_wout_stopwords)+len(texto_03_token_wout_stopwords)+len(texto_04_token_wout_stopwords)+len(texto_05_token_wout_stopwords))



24
27
18
21
21
111


In [33]:
#Creacion de la BoW
dicc_textos = {"texto01":texto_01_token_wout_stopwords, "texto02": texto_02_token_wout_stopwords, "texto03": texto_03_token_wout_stopwords, "texto04": texto_04_token_wout_stopwords, "texto05": texto_05_token_wout_stopwords }


In [34]:
print(dicc_textos)

{'texto01': ['si', 'bimbo', 'pretende', 'seguir', 'oponie', 'ndose', 'etiquetado', 'claro', 'medida', 'puede', 'salvar', 'mejorar', 'vida', 'miles', 'nin', 'frente', 'obesidad', 'diabetes', 'quiza', 'deberi', 'amos', 'plantearnos', 'sacarlos', 'cotidianidad'], 'texto02': ['constancia', 'poner', 'etiquetado', 'salve', 'miles', 'vidas', 'si', 'disminuyo', 'consumo', 'comida', 'chatarra', 'ieps', 'metieron', 'precisamente', 'fin', 'inhibir', 'consumo', 'ima', 'genes', 'gra', 'ficas', 'cajetillas', 'difi', 'cilmente', 'etiquetado', 'hara', 'diferencia'], 'texto03': ['pregunta', 'seri', 'insisten', 'invitar', 'ijustine', 'eventos', 'samsung', 'si', 'sabemos', 'apple', 'fan', 'boy', 'serio', 've', 'falsa', 'fingiendo', 'intere', 's'], 'texto04': ['celebrar', 'san', 'valentin', 'voy', 'contar', 'historia', 'novio', 'hu', 'ngaro', 'di', 'querer', 'reunio', 'n', 'familiar', 'casi', 'mato', 'abuelita', 'taji', 'n', 'aga', 'rrense'], 'texto05': ['celebrar', 'san', 'valentin', 'voy', 'contar', 'hi

In [43]:
dicc_terminos = {}

for text  in dicc_textos:
    for word  in dicc_textos[text]:
        if(word in dicc_terminos): #incrementar palabras al diccionario.
         dicc_terminos[word] = dicc_terminos[word] + 1
         print(word , "in", "dicc_terminos")
            
        elif(word not in dicc_terminos):
         dicc_terminos[word] = 1
         print(word, "NOT IN", "dicc_terminos")
                
    


si NOT IN dicc_terminos
bimbo NOT IN dicc_terminos
pretende NOT IN dicc_terminos
seguir NOT IN dicc_terminos
oponie NOT IN dicc_terminos
ndose NOT IN dicc_terminos
etiquetado NOT IN dicc_terminos
claro NOT IN dicc_terminos
medida NOT IN dicc_terminos
puede NOT IN dicc_terminos
salvar NOT IN dicc_terminos
mejorar NOT IN dicc_terminos
vida NOT IN dicc_terminos
miles NOT IN dicc_terminos
nin NOT IN dicc_terminos
frente NOT IN dicc_terminos
obesidad NOT IN dicc_terminos
diabetes NOT IN dicc_terminos
quiza NOT IN dicc_terminos
deberi NOT IN dicc_terminos
amos NOT IN dicc_terminos
plantearnos NOT IN dicc_terminos
sacarlos NOT IN dicc_terminos
cotidianidad NOT IN dicc_terminos
constancia NOT IN dicc_terminos
poner NOT IN dicc_terminos
etiquetado in dicc_terminos
salve NOT IN dicc_terminos
miles in dicc_terminos
vidas NOT IN dicc_terminos
si in dicc_terminos
disminuyo NOT IN dicc_terminos
consumo NOT IN dicc_terminos
comida NOT IN dicc_terminos
chatarra NOT IN dicc_terminos
ieps NOT IN dicc_te

In [44]:
print(len(dicc_terminos))

83


In [45]:
dicc_terminos

{'si': 3,
 'bimbo': 1,
 'pretende': 1,
 'seguir': 1,
 'oponie': 1,
 'ndose': 1,
 'etiquetado': 3,
 'claro': 1,
 'medida': 1,
 'puede': 1,
 'salvar': 1,
 'mejorar': 1,
 'vida': 1,
 'miles': 2,
 'nin': 1,
 'frente': 1,
 'obesidad': 1,
 'diabetes': 1,
 'quiza': 1,
 'deberi': 1,
 'amos': 1,
 'plantearnos': 1,
 'sacarlos': 1,
 'cotidianidad': 1,
 'constancia': 1,
 'poner': 1,
 'salve': 1,
 'vidas': 1,
 'disminuyo': 1,
 'consumo': 2,
 'comida': 1,
 'chatarra': 1,
 'ieps': 1,
 'metieron': 1,
 'precisamente': 1,
 'fin': 1,
 'inhibir': 1,
 'ima': 1,
 'genes': 1,
 'gra': 1,
 'ficas': 1,
 'cajetillas': 1,
 'difi': 1,
 'cilmente': 1,
 'hara': 1,
 'diferencia': 1,
 'pregunta': 1,
 'seri': 1,
 'insisten': 1,
 'invitar': 1,
 'ijustine': 1,
 'eventos': 1,
 'samsung': 1,
 'sabemos': 1,
 'apple': 1,
 'fan': 1,
 'boy': 1,
 'serio': 1,
 've': 1,
 'falsa': 1,
 'fingiendo': 1,
 'intere': 1,
 's': 1,
 'celebrar': 2,
 'san': 2,
 'valentin': 2,
 'voy': 2,
 'contar': 2,
 'historia': 2,
 'novio': 2,
 'hu': 2,
 '

In [46]:
#MATRIZ TERMINO DOCUMENTO(BINARIA)

matrix = np.zeros((len(dicc_textos),len(dicc_terminos) )) #pre-asignacion de la matriz
matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.

In [50]:
i=0
j=0

for word_termns in dicc_terminos:
    for word_texts in dicc_textos:
        
        if(word_termns in dicc_textos[word_texts]): #si esta
            print(word_termns, "IN ", word_texts) 
            matrix[j,i] = 1
        
        elif(word_termns not in dicc_textos[word_texts]): #si no esta.
            print(word_termns, "NOT IN",word_texts)
            matrix[j,i] = 0
        
        print("se agrego: ", matrix[j,i], "en: ", j , i)
        
        j= j+1
        
    
    j=0
    
    i=i+1
        

si IN  texto01
se agrego:  1.0 en:  0 0
si IN  texto02
se agrego:  1.0 en:  1 0
si IN  texto03
se agrego:  1.0 en:  2 0
si NOT IN texto04
se agrego:  0.0 en:  3 0
si NOT IN texto05
se agrego:  0.0 en:  4 0
bimbo IN  texto01
se agrego:  1.0 en:  0 1
bimbo NOT IN texto02
se agrego:  0.0 en:  1 1
bimbo NOT IN texto03
se agrego:  0.0 en:  2 1
bimbo NOT IN texto04
se agrego:  0.0 en:  3 1
bimbo NOT IN texto05
se agrego:  0.0 en:  4 1
pretende IN  texto01
se agrego:  1.0 en:  0 2
pretende NOT IN texto02
se agrego:  0.0 en:  1 2
pretende NOT IN texto03
se agrego:  0.0 en:  2 2
pretende NOT IN texto04
se agrego:  0.0 en:  3 2
pretende NOT IN texto05
se agrego:  0.0 en:  4 2
seguir IN  texto01
se agrego:  1.0 en:  0 3
seguir NOT IN texto02
se agrego:  0.0 en:  1 3
seguir NOT IN texto03
se agrego:  0.0 en:  2 3
seguir NOT IN texto04
se agrego:  0.0 en:  3 3
seguir NOT IN texto05
se agrego:  0.0 en:  4 3
oponie IN  texto01
se agrego:  1.0 en:  0 4
oponie NOT IN texto02
se agrego:  0.0 en:  1 4
op

se agrego:  0.0 en:  2 39
gra NOT IN texto04
se agrego:  0.0 en:  3 39
gra NOT IN texto05
se agrego:  0.0 en:  4 39
ficas NOT IN texto01
se agrego:  0.0 en:  0 40
ficas IN  texto02
se agrego:  1.0 en:  1 40
ficas NOT IN texto03
se agrego:  0.0 en:  2 40
ficas NOT IN texto04
se agrego:  0.0 en:  3 40
ficas NOT IN texto05
se agrego:  0.0 en:  4 40
cajetillas NOT IN texto01
se agrego:  0.0 en:  0 41
cajetillas IN  texto02
se agrego:  1.0 en:  1 41
cajetillas NOT IN texto03
se agrego:  0.0 en:  2 41
cajetillas NOT IN texto04
se agrego:  0.0 en:  3 41
cajetillas NOT IN texto05
se agrego:  0.0 en:  4 41
difi NOT IN texto01
se agrego:  0.0 en:  0 42
difi IN  texto02
se agrego:  1.0 en:  1 42
difi NOT IN texto03
se agrego:  0.0 en:  2 42
difi NOT IN texto04
se agrego:  0.0 en:  3 42
difi NOT IN texto05
se agrego:  0.0 en:  4 42
cilmente NOT IN texto01
se agrego:  0.0 en:  0 43
cilmente IN  texto02
se agrego:  1.0 en:  1 43
cilmente NOT IN texto03
se agrego:  0.0 en:  2 43
cilmente NOT IN texto

In [51]:
matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
        1., 1., 1., 1.

In [52]:
matrix.shape

(5, 83)

In [53]:
bin_cos_t01_t02 = dot(matrix[0],matrix[1])/(norm(matrix[0])*norm(matrix[1]))
bin_cos_t01_t02

0.12247448713915891

In [54]:
bin_cos_t01_t03 = dot(matrix[0],matrix[2])/(norm(matrix[0])*norm(matrix[2]))
bin_cos_t01_t03

0.04811252243246882

In [55]:
bin_cos_t01_t04 = dot(matrix[0],matrix[3])/(norm(matrix[0])*norm(matrix[3]))
bin_cos_t01_t04

0.0

In [56]:
bin_cos_t01_t05 = dot(matrix[0],matrix[4])/(norm(matrix[0])*norm(matrix[4]))
bin_cos_t01_t05

0.0

In [57]:
bin_cos_t02_t03 = dot(matrix[1],matrix[2])/(norm(matrix[1])*norm(matrix[2]))
bin_cos_t02_t03

0.047140452079103175

In [58]:
bin_cos_t02_t04 = dot(matrix[1],matrix[3])/(norm(matrix[1])*norm(matrix[3]))
bin_cos_t02_t04

0.0

In [59]:
bin_cos_t02_t05 = dot(matrix[1],matrix[4])/(norm(matrix[1])*norm(matrix[4]))
bin_cos_t02_t05

0.0

In [60]:
bin_cos_t03_t04 = dot(matrix[2],matrix[3])/(norm(matrix[2])*norm(matrix[3]))
bin_cos_t03_t04

0.0

In [62]:
bin_cos_t03_t05 = dot(matrix[2],matrix[4])/(norm(matrix[2])*norm(matrix[4]))
bin_cos_t03_t05

0.0

In [63]:
bin_cos_t04_t05 = dot(matrix[3],matrix[4])/(norm(matrix[3])*norm(matrix[4]))
bin_cos_t04_t05

0.9999999999999998

In [64]:
matrix = np.zeros((len(dicc_textos), len(dicc_terminos)))
matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.

In [66]:
i=0
j=0

for word_terms in dicc_terminos: #todos los terminos.
    for word_texts in dicc_textos:  #todos los textos.
        
        if(word_terms in dicc_textos[word_texts]):
            print(word_terms, "IN " , word_texts)
        
            matrix[j,i] = dicc_terminos[word_terms]
        
        elif(word_terms not in  dicc_textos[word_texts]):
            print(word_terms, "NOT IN" , word_texts)
            
            matrix[j,i]= 0
            
        print("se agrego" , matrix[j,i], "en: " , j, i )
        
        j = j+1
        
    j=0
    
    i=i+1

si IN  texto01
se agrego 3.0 en:  0 0
si IN  texto02
se agrego 3.0 en:  1 0
si IN  texto03
se agrego 3.0 en:  2 0
si NOT IN texto04
se agrego 0.0 en:  3 0
si NOT IN texto05
se agrego 0.0 en:  4 0
bimbo IN  texto01
se agrego 1.0 en:  0 1
bimbo NOT IN texto02
se agrego 0.0 en:  1 1
bimbo NOT IN texto03
se agrego 0.0 en:  2 1
bimbo NOT IN texto04
se agrego 0.0 en:  3 1
bimbo NOT IN texto05
se agrego 0.0 en:  4 1
pretende IN  texto01
se agrego 1.0 en:  0 2
pretende NOT IN texto02
se agrego 0.0 en:  1 2
pretende NOT IN texto03
se agrego 0.0 en:  2 2
pretende NOT IN texto04
se agrego 0.0 en:  3 2
pretende NOT IN texto05
se agrego 0.0 en:  4 2
seguir IN  texto01
se agrego 1.0 en:  0 3
seguir NOT IN texto02
se agrego 0.0 en:  1 3
seguir NOT IN texto03
se agrego 0.0 en:  2 3
seguir NOT IN texto04
se agrego 0.0 en:  3 3
seguir NOT IN texto05
se agrego 0.0 en:  4 3
oponie IN  texto01
se agrego 1.0 en:  0 4
oponie NOT IN texto02
se agrego 0.0 en:  1 4
oponie NOT IN texto03
se agrego 0.0 en:  2 4
o

se agrego 0.0 en:  3 52
samsung NOT IN texto05
se agrego 0.0 en:  4 52
sabemos NOT IN texto01
se agrego 0.0 en:  0 53
sabemos NOT IN texto02
se agrego 0.0 en:  1 53
sabemos IN  texto03
se agrego 1.0 en:  2 53
sabemos NOT IN texto04
se agrego 0.0 en:  3 53
sabemos NOT IN texto05
se agrego 0.0 en:  4 53
apple NOT IN texto01
se agrego 0.0 en:  0 54
apple NOT IN texto02
se agrego 0.0 en:  1 54
apple IN  texto03
se agrego 1.0 en:  2 54
apple NOT IN texto04
se agrego 0.0 en:  3 54
apple NOT IN texto05
se agrego 0.0 en:  4 54
fan NOT IN texto01
se agrego 0.0 en:  0 55
fan NOT IN texto02
se agrego 0.0 en:  1 55
fan IN  texto03
se agrego 1.0 en:  2 55
fan NOT IN texto04
se agrego 0.0 en:  3 55
fan NOT IN texto05
se agrego 0.0 en:  4 55
boy NOT IN texto01
se agrego 0.0 en:  0 56
boy NOT IN texto02
se agrego 0.0 en:  1 56
boy IN  texto03
se agrego 1.0 en:  2 56
boy NOT IN texto04
se agrego 0.0 en:  3 56
boy NOT IN texto05
se agrego 0.0 en:  4 56
serio NOT IN texto01
se agrego 0.0 en:  0 57
serio 

In [67]:
matrix

array([[3., 1., 1., 1., 1., 1., 3., 1., 1., 1., 1., 1., 1., 2., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [3., 0., 0., 0., 0., 0., 3., 0., 0., 0., 0., 0., 0., 2., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 2., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
        1., 1., 1., 1.

In [68]:
matrix.shape

(5, 83)

In [69]:
    matrix[0]

array([3., 1., 1., 1., 1., 1., 3., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [70]:
matrix[1]

array([3., 0., 0., 0., 0., 0., 3., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [71]:
matrix[2]

array([3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [72]:
bin_cos_t01_t02 = dot(matrix[0],matrix[1])/(norm(matrix[0])*norm(matrix[1]))
bin_cos_t01_t02

0.48937245863014206

In [73]:
bin_cos_t01_t03 = dot(matrix[0],matrix[2])/(norm(matrix[0])*norm(matrix[2]))
bin_cos_t01_t03

0.26916687204956063

In [74]:
bin_cos_t01_t04 = dot(matrix[0],matrix[3])/(norm(matrix[0])*norm(matrix[3]))
bin_cos_t01_t04

0.0

In [75]:
bin_cos_t01_t05 = dot(matrix[0],matrix[4])/(norm(matrix[0])*norm(matrix[4]))
bin_cos_t01_t05

0.0

In [76]:
bin_cos_t02_t03 = dot(matrix[1],matrix[2])/(norm(matrix[1])*norm(matrix[2]))
bin_cos_t02_t03

0.2574583054607804

In [77]:
bin_cos_t02_t04 = dot(matrix[1],matrix[3])/(norm(matrix[1])*norm(matrix[3]))
bin_cos_t02_t04

0.0

In [78]:
bin_cos_t02_t05 = dot(matrix[1],matrix[4])/(norm(matrix[1])*norm(matrix[4]))
bin_cos_t02_t05

0.0

In [79]:
bin_cos_t03_t04 = dot(matrix[2],matrix[3])/(norm(matrix[2])*norm(matrix[3]))
bin_cos_t03_t04

0.0

In [80]:
bin_cos_t03_t05 = dot(matrix[2],matrix[4])/(norm(matrix[2])*norm(matrix[4]))
bin_cos_t03_t05

0.0

In [81]:
bin_cos_t04_t05 = dot(matrix[3],matrix[4])/(norm(matrix[3])*norm(matrix[4]))
bin_cos_t04_t05

1.0000000000000002